command_timeout = 1000

[kubernetes]
disabled = false
symbol = 'â›´ï¸  '

[gradle]
disabled = true

[java]
style = 'yellow'
symbol = 'â˜•ï¸ '

[python]
disabled = true

[git_status]
conflicted = 'ğŸ’¥'
staged = 'ğŸ§©'
modified = 'âš¡ï¸'
stashed = 'ğŸ’°'
diverged = 'ğŸ”€'
deleted = 'ğŸ—‘ï¸ '

[package]
disabled = true
